services:
  db:
    image: mariadb:11
    volumes:
      - database:/var/lib/mysql:rw
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    volumes:
      - nginx:/app/nginx:ro
      - static:/app/static:rw
      - media:/app/media:rw
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SECRET_KEY
      - SITE_URL
      - DEBUG=0
    depends_on:
      - db

  nginx:
    image: nginx:1
    ports:
      - 8001:8000
    volumes:
      - nginx:/etc/nginx/conf.d:ro
      - static:/app/static:ro
      - media:/app/media:ro
    depends_on:
      - app

volumes:
  database:
  static:
  media:
  nginx:
