services:
  db:
    image: mariadb:11
    volumes:
      - database:/var/lib/mysql:rw
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    volumes:
      - static:/app/static:rw
      - media:/app/media:rw
      - nginx:/app/nginx:ro
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SECRET_KEY
      - SITE_URL
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx:/etc/nginx/conf.d:ro
      - static:/app/static:ro
      - media:/app/media:ro
      - certbot:/var/www/html/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path /var/www/html/ -d $SITE_URL -m $EMAIL --non-interactive --agree-tos --keep-until-expiring
    volumes:
      - certbot:/var/www/html/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    environment:
      - EMAIL
      - SITE_URL
    depends_on:
      - nginx

volumes:
  database:
  static:
  media:
  certbot:
  nginx: