services:
  db:
    image: mariadb:11
    volumes:
      - database:/var/lib/mysql:rw
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    volumes:
      - .:/app
      - static:/app/static:rw
      - media:/app/media:rw
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SECRET_KEY
      - ALLOWED_HOSTS
      - DEBUG=0
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - static:/app/static:ro
      - media:/app/media:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path /var/www/certbot/ -d bdmanga.insalgo.fr --agree-tos --email $EMAIL
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    environment:
      - email
    depends_on:
      - nginx

volumes:
  database:
  static:
  media: