services:
  db:
    image: mariadb:11
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - database
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

  app:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - static:/app/static:rw
      - media:/app/media:rw
    networks:
      - database
      - nginx
    environment:
      - DB_HOST=db
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SECRET_KEY
      - SITE_URL
      - DEBUG
    depends_on:
      - db

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - static:/app/static:ro
      - media:/app/media:ro
    networks:
      - nginx
    depends_on:
      - app

networks:
  database:
    driver: bridge
  nginx:
    driver: bridge

volumes:
  database:
  static:
  media: