# Generated by Django 4.2.4 on 2023-09-21 05:22

import asso.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_squashed_0016_delete_loan_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tel', models.CharField(blank=True, max_length=12, verbose_name='tel')),
                ('bail', models.FloatField(default=0, help_text='en euros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='caution déposée')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('can_make_loan', models.BooleanField(default=True, help_text='Les membres + peuvent emprunter des livres', verbose_name='membre +')),
                ('is_alir_member', models.BooleanField(default=False, verbose_name="membre de l'ALIR")),
                ('has_paid', models.BooleanField(default=True, help_text='Ce champ est réinitialisé tous les ans', verbose_name='a cotisé')),
                ('account', models.OneToOneField(blank=True, help_text='compte pour accéder à ce site', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='compte')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'membre',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_start', models.DateField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('loan_return', models.DateField(blank=True, help_text="laisser vide jusqu'au retour", null=True, verbose_name='date de retour')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.book', verbose_name='livre')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asso.member', validators=[asso.models.can_make_loan], verbose_name='membre')),
            ],
            options={
                'verbose_name': 'emprunt',
                'ordering': ['-loan_start'],
                'unique_together': {('member', 'book', 'loan_start')},
            },
        ),
    ]
