# Generated by Django 5.2.3 on 2025-06-18 05:19

import asso.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('asso', '0001_squashed_0012_remove_loan_late_return'), ('asso', '0013_remove_member_is_alir_member_alter_member_account_and_more'), ('asso', '0014_alter_member_tel'), ('asso', '0015_news'), ('asso', '0016_alter_news_options_news_date_news_slug_news_title_and_more'), ('asso', '0017_news_summary_alter_news_date'), ('asso', '0018_news_visible_alter_news_content_alter_news_summary'), ('asso', '0019_page_remove_news_visible_alter_news_date'), ('asso', '0020_alter_news_date_alter_news_slug'), ('asso', '0021_remove_member_can_make_loan_member_plus_membership_and_more'), ('asso', '0022_rename_bail_member_deposit')]

    initial = True

    dependencies = [
        ('inventory', '0001_squashed_0027_book_added_by_alter_book_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tel', models.CharField(blank=True, max_length=15, verbose_name='tel')),
                ('deposit', models.FloatField(default=0, help_text='en euros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='caution déposée')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
                ('plus_membership', models.BooleanField(default=0, help_text='Les membres+ peuvent emprunter des livres.', verbose_name='membre+')),
                ('has_paid', models.BooleanField(help_text='Ce champ est réinitialisé tous les ans.', verbose_name='a cotisé')),
                ('account', models.OneToOneField(blank=True, help_text='Compte pour accéder à la partie admin du site (optionel).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='compte')),
                ('last_name', models.CharField(max_length=255, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'membre',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('identifier', models.SlugField(unique=True, verbose_name='identifiant')),
                ('content', models.TextField(blank=True, help_text='Le texte doit utiliser le format Markdown.', verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'page',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='\n        Le texte doit utiliser le format Markdown.\n        Pour les images, déposez les sur le Google Drive et utilisez le lien de partage.\n    ', verbose_name='contenu')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text="\n        Si la date est dans le futur, l'article n'apparaitra pas dans les actualités avant cette date.\n        Il reste accessible via son adresse.\n    ", verbose_name='date')),
                ('slug', models.SlugField(help_text="Dernière partie de l'URL à laquelle on pourra trouver cet article.", unique=True, verbose_name='adresse')),
                ('title', models.CharField(default=datetime.datetime(2025, 6, 8, 18, 30, 44, 560286, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='titre')),
                ('summary', models.CharField(blank=True, max_length=400, verbose_name='résumé')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'actualité',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_start', models.DateField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('loan_return', models.DateField(blank=True, help_text="Laisser vide jusqu'au retour.", null=True, verbose_name='date de retour')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.book', verbose_name='livre')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asso.member', validators=[asso.models.can_make_loan], verbose_name='membre')),
            ],
            options={
                'verbose_name': 'emprunt',
                'ordering': ['-loan_start'],
                'unique_together': {('member', 'book', 'loan_start')},
            },
        ),
    ]
