# Generated by Django 4.2.4 on 2023-09-08 15:11

import django.core.validators
import django.utils.datetime_safe
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0016_delete_loan_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('tel', models.CharField(blank=True, max_length=12, verbose_name='tel')),
                ('max_loans', models.PositiveIntegerField(default=1, help_text="nombre d'emprunts simultanés maximum", verbose_name="nombre d'emprunts maximum")),
                ('loan_length', models.PositiveIntegerField(default=30, help_text="durée maximale d'un emprunt en jours", verbose_name="durée d'emprunt")),
                ('bail', models.FloatField(default=0, help_text='en euros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='caution')),
                ('last_loan', models.DateField(blank=True, editable=False, null=True, verbose_name='date du dernier emprunt')),
                ('role_bdm', models.CharField(choices=[('member', 'Membre'), ('member+', 'Membre +'), ('not member', 'Non membre'), ('board', 'Bureau')], max_length=64, verbose_name='rôle au Club BDManga')),
                ('role_alir', models.CharField(choices=[('member', 'Membre'), ('member+', 'Membre +'), ('not member', 'Non membre'), ('board', 'Bureau')], max_length=64, verbose_name="rôle à l'Alir")),
                ('archived', models.BooleanField(default=False, verbose_name='ancien membre')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name="date d'inscription")),
            ],
            options={
                'verbose_name': 'membre',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_start', models.DateField(default=django.utils.datetime_safe.datetime.now, verbose_name='date de début')),
                ('late_return', models.DateField(editable=False, help_text='date avant laquelle le livre devra être rendu', verbose_name='date de retour maximum')),
                ('loan_return', models.DateField(blank=True, help_text="laisser vide jusqu'au retour", null=True, verbose_name='date de retour')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.book', verbose_name='livre')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asso.member', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'emprunt',
                'ordering': ['-loan_start'],
                'unique_together': {('member', 'book', 'loan_start')},
            },
        ),
    ]
