# Generated by Django 4.2.4 on 2023-09-08 16:15

import django.db.models.deletion
from django.db import migrations, models

import asso.models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asso.member', validators=[asso.models.can_make_loan], verbose_name='membre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_alir',
            field=models.CharField(choices=[('member', 'Membre'), ('member+', 'Membre +'), ('not member', 'Non membre')], max_length=64, verbose_name="rôle à l'Alir"),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_bdm',
            field=models.CharField(choices=[('member', 'Membre'), ('member+', 'Membre +'), ('not member', 'Non membre')], max_length=64, verbose_name='rôle au Club BDManga'),
        ),
    ]
