# Generated by Django 4.2.4 on 2023-09-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0002_alter_loan_member_alter_member_role_alir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_make_loan',
            field=models.BooleanField(default=True, help_text='Les membres + peuvent emprunter des livres', verbose_name='membre +'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='is_alir_member',
            field=models.BooleanField(default=False, verbose_name="Membre à l'ALIR"),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_alir',
            field=models.CharField(choices=[('not member', 'Non membre'), ('member', 'Membre'), ('member+', 'Membre +')], default='not member', max_length=64, verbose_name="status à l'Alir"),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_bdm',
            field=models.CharField(choices=[('not member', 'Non membre'), ('member', 'Membre'), ('member+', 'Membre +')], max_length=64, verbose_name='status au Club BDManga'),
        ),
    ]
