# Generated by Django 4.2.4 on 2023-09-08 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0003_member_can_make_loan_member_is_alir_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_loan',
        ),
        migrations.RemoveField(
            model_name='member',
            name='loan_length',
        ),
        migrations.RemoveField(
            model_name='member',
            name='max_loans',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role_alir',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role_bdm',
        ),
        migrations.AlterField(
            model_name='member',
            name='bail',
            field=models.FloatField(default=0, help_text='en euros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='caution déposée'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_alir_member',
            field=models.BooleanField(default=False, verbose_name="Membre de l'ALIR"),
        ),
    ]
