# Generated by Django 4.2.4 on 2023-09-08 19:09

import asso.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_delete_loan_delete_member'),
        ('asso', '0004_remove_member_last_loan_remove_member_loan_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='archived',
        ),
        migrations.AddField(
            model_name='member',
            name='has_paid',
            field=models.BooleanField(default=True, help_text='Ce champ est réinitialisé tous les ans', verbose_name='a cotisé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(default=asso.models._last_loan_book, on_delete=django.db.models.deletion.CASCADE, to='inventory.book', verbose_name='livre'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(default=asso.models._last_loan_member, on_delete=django.db.models.deletion.CASCADE, to='asso.member', validators=[asso.models.can_make_loan], verbose_name='membre'),
        ),
    ]
