# Generated by Django 4.2.4 on 2023-09-08 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asso', '0005_remove_member_archived_member_has_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_alir_member',
            field=models.BooleanField(default=False, verbose_name="membre de l'ALIR"),
        ),
    ]
