# Generated by Django 4.2.4 on 2023-09-08 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asso', '0006_member_account_alter_member_is_alir_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
    ]
