# Generated by Django 4.2.4 on 2023-09-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0007_alter_member_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='prénom'),
        ),
    ]
