# Generated by Django 4.2.4 on 2023-09-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0009_rename_name_member_first_name_alter_member_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='mail',
            new_name='email',
        ),
    ]
