# Generated by Django 4.2.4 on 2023-09-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asso', '0010_rename_mail_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.OneToOneField(blank=True, help_text='compte pour accéder à ce site', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
    ]
