# Generated by Django 4.2.4 on 2023-09-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0011_alter_member_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='late_return',
        ),
    ]
