# Generated by Django 4.2.4 on 2023-09-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asso', '0001_squashed_0012_remove_loan_late_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_alir_member',
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.OneToOneField(blank=True, help_text='compte pour accéder à ce site', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
        migrations.AlterField(
            model_name='member',
            name='can_make_loan',
            field=models.BooleanField(help_text='Les membres + peuvent emprunter des livres', verbose_name='membre +'),
        ),
        migrations.AlterField(
            model_name='member',
            name='has_paid',
            field=models.BooleanField(help_text='Ce champ est réinitialisé tous les ans', verbose_name='a cotisé'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='nom'),
        ),
    ]
