# Generated by Django 4.2.4 on 2023-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0013_remove_member_is_alir_member_alter_member_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tel',
            field=models.CharField(blank=True, max_length=15, verbose_name='tel'),
        ),
    ]
