# Generated by Django 4.2.20 on 2025-06-08 18:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0015_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'actualité'},
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text="dernière partie de l'URL à laquelle on pourra trouver cet article", unique=True, verbose_name='adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=datetime.datetime(2025, 6, 8, 18, 30, 44, 560286, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='titre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='le texte doit utiliser le format Markdown', verbose_name='contenu'),
        ),
    ]
