# Generated by Django 4.2.20 on 2025-06-09 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0016_alter_news_options_news_date_news_slug_news_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=300, verbose_name='résumé'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
