# Generated by Django 4.2.20 on 2025-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0017_news_summary_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='\n        Le texte doit utiliser le format Markdown.\n        Pour les images, déposez les sur le Google Drive et utilisez le lien de partage.\n    ', verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=400, verbose_name='résumé'),
        ),
    ]
