# Generated by Django 4.2.20 on 2025-06-09 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0018_news_visible_alter_news_content_alter_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('identifier', models.SlugField(unique=True, verbose_name='identifiant')),
                ('content', models.TextField(blank=True, help_text='Le texte doit utiliser le format Markdown.', verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'page',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='visible',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text="si la date est dans le futur, l'article ne sera pas visible avant", verbose_name='date'),
        ),
    ]
