# Generated by Django 4.2.20 on 2025-06-14 23:42

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0019_page_remove_news_visible_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now, help_text="\n        Si la date est dans le futur, l'article n'apparaitra pas dans les actualités avant cette date.\n        Il reste accessible via son adresse.\n    ", verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text="Dernière partie de l'URL à laquelle on pourra trouver cet article.", unique=True, verbose_name='adresse'),
        ),
    ]
