# Generated by Django 5.2.3 on 2025-06-17 06:07

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0020_alter_news_date_alter_news_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='can_make_loan',
            new_name='plus_membership',
        ),
        migrations.AlterField(
            model_name='member',
            name='plus_membership',
            field=models.BooleanField(default=0, help_text='Les membres+ peuvent emprunter des livres.', verbose_name='membre+'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='has_paid',
            field=models.BooleanField(help_text='Ce champ est réinitialisé tous les ans.', verbose_name='a cotisé'),
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.OneToOneField(blank=True, help_text='Compte pour accéder à la partie admin du site (optionel).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateField(blank=True, help_text="Laisser vide jusqu'au retour.", null=True,
                                   verbose_name='date de retour'),
        ),
    ]
