# Generated by Django 5.2.3 on 2025-06-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0021_remove_member_can_make_loan_member_plus_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='bail',
            new_name='deposit',
        ),
    ]
