# Generated by Django 5.2.3 on 2025-06-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0001_squashed_0022_rename_bail_member_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plus_membership',
            field=models.BooleanField(help_text='Les membres+ peuvent emprunter des livres.', verbose_name='membre+'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre'),
        ),
    ]
