# Generated by Django 5.2.17 on 2026-09-27 14:26

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F

def copy_old_date(apps, schema_editor):
    news = apps.get_model("asso", "news")
    news.objects.all().update(pub_date=F("date"))

class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0024_migrate_membership_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, help_text="\n        L'article n'apparaîtra qu'à partir de la date de publication, mais il est toujours accessible via son adresse.\n    ", verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text="\n        Date de création ou de l'évènement en question, affichée avec l'article.\n    ", verbose_name='date'),
        ),
        migrations.RunPython(code=copy_old_date)
    ]
