# Generated by Django 4.2.4 on 2023-09-21 05:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'auteur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'éditeur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{5}$')], verbose_name='référence')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('type', models.CharField(choices=[('bd', 'BD'), ('manga', 'Manga'), ('comics', 'Comics'), ('novel', 'Roman')], max_length=16, verbose_name='type')),
                ('authors', models.ManyToManyField(to='inventory.author', verbose_name='auteurs')),
                ('editors', models.ManyToManyField(to='inventory.editor', verbose_name='éditeurs')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.genre', verbose_name='genre')),
            ],
            options={
                'verbose_name': 'série',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z0-9]{5}[0-9]{5}$')], verbose_name='cote')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nom')),
                ('volume_nb', models.PositiveIntegerField(verbose_name='volume')),
                ('duplicate_nb', models.PositiveIntegerField(default=1, verbose_name='numéro de duplicata')),
                ('condition', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='état')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name="date d'ajout")),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.series', verbose_name='série')),
                ('available', models.BooleanField(default=True, editable=False, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'livre',
                'ordering': ['id'],
                'unique_together': {('series', 'volume_nb', 'duplicate_nb')},
            },
        ),
    ]
