# Generated by Django 4.2.4 on 2023-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_member_last_loan_alter_series_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_loan',
            field=models.DateField(editable=False, null=True, verbose_name='date du dernier emprunt'),
        ),
    ]
