# Generated by Django 4.2.4 on 2023-09-05 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_member_last_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archivé'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_return',
            field=models.DateField(help_text="date à partir de laquelle l'emprunt est en retard", null=True, verbose_name='date de retard'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateField(null=True, verbose_name='date de retour'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bail',
            field=models.FloatField(default=0, help_text='en euros', validators=[django.core.validators.MinValueValidator(0)], verbose_name='caution'),
        ),
    ]
