# Generated by Django 4.2.4 on 2023-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_book_condition_alter_loan_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateField(blank=True, null=True, verbose_name='date de retour'),
        ),
    ]
