# Generated by Django 4.2.4 on 2023-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_loan_loan_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='late_return',
            field=models.DateField(blank=True, help_text="date à partir de laquelle l'emprunt est en retard", null=True, verbose_name='date de retard'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_loan',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='date du dernier emprunt'),
        ),
    ]
