# Generated by Django 4.2.4 on 2023-09-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_author_options_alter_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'livre'},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['name'], 'verbose_name': 'éditeur'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_start'], 'verbose_name': 'prêt'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': 'membre'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['id'], 'verbose_name': 'série'},
        ),
    ]
