# Generated by Django 4.2.4 on 2023-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_series_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_added'], 'verbose_name': 'membre'},
        ),
        migrations.AlterField(
            model_name='book',
            name='volume_nb',
            field=models.PositiveIntegerField(verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_bdm',
            field=models.CharField(choices=[('member', 'Membre'), ('member+', 'Membre +'), ('not member', 'Non membre'), ('board', 'Bureau')], max_length=64, verbose_name='rôle au Club BDManga'),
        ),
    ]
