# Generated by Django 4.2.4 on 2023-09-06 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_member_options_alter_book_volume_nb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_start'], 'verbose_name': 'emprunt'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(help_text='la recherche se fait par cote', on_delete=django.db.models.deletion.CASCADE, to='inventory.book', verbose_name='livre'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_return',
            field=models.DateField(blank=True, help_text='date avant laquelle le livre devra être rendu', null=True, verbose_name='date de retour maximum'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_start',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now, verbose_name='date de début'),
        ),
    ]
