# Generated by Django 4.2.4 on 2023-09-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_loan_options_alter_loan_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.book', verbose_name='livre'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateField(blank=True, help_text="laisser vide jusqu'au retour", null=True, verbose_name='date de retour'),
        ),
    ]
