# Generated by Django 4.2.4 on 2023-09-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_loan_book_alter_loan_loan_return'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'genre'},
        ),
    ]
