# Generated by Django 4.2.4 on 2023-09-08 14:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_genre_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='archived',
        ),
        migrations.AlterField(
            model_name='book',
            name='duplicate_nb',
            field=models.PositiveIntegerField(default=1, verbose_name='numéro de duplicata'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z0-9]{5}[0-9]{5}$')], verbose_name='cote'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='late_return',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='date avant laquelle le livre devra être rendu', verbose_name='date de retour maximum'),
            preserve_default=False,
        ),
    ]
