# Generated by Django 4.2.4 on 2023-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_book_available_remove_loan_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True, editable=False, verbose_name='disponible'),
        ),
    ]
