# Generated by Django 4.2.4 on 2023-09-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_book_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
