# Generated by Django 4.2.4 on 2023-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0016_delete_loan_delete_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name': 'série'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('bd', 'BD'), ('manga', 'manga'), ('comics', 'comic'), ('novel', 'roman')], max_length=16, verbose_name='type'),
        ),
    ]
