# Generated by Django 4.2.20 on 2025-06-08 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_series_options_remove_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.series', verbose_name='série'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume_nb',
            field=models.PositiveIntegerField(verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{5}$')], verbose_name='code'),
        ),
    ]
