# Generated by Django 4.2.20 on 2025-06-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_book_condition_alter_book_series_and_more'),
    ]

    operations = [

        # Remove the old foreign key constraint
        migrations.RunSQL(
            sql="-- Foreign key will be handled by manual SQL script",
            reverse_sql="-- Reverse not implemented"
        ),

        # Modify the Book model
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='book',
            name='call_number',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z0-9]{5}[0-9]{5}$')], verbose_name='cote'),
        ),

        # Mark this as a no-op since we're handling it manually
        migrations.RunSQL(
            sql="-- Actual schema changes handled by manual SQL script",
            reverse_sql="-- Reverse not implemented"
        ),
    ]
