# Generated by Django 4.2.20 on 2025-06-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_book_change_pk'),
    ]

    operations = [
        # Manual migration with SQL script needed
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.AddField(
            model_name='series',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='series',
            name='code',
            field=models.CharField(db_index=True, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{5}$')], verbose_name='code'),
        ),
    ]
