# Generated by Django 4.2.20 on 2025-06-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_series_change_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['call_number'], 'verbose_name': 'livre'},
        ),
    ]
