# Generated by Django 5.2.3 on 2025-06-15 00:37

import django.core.validators
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='call_number',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.text.LPad(django.db.models.functions.comparison.Cast('genre__id', models.CharField()), 2, models.Value('0')), 'code'), output_field=models.CharField(max_length=7, unique=True, verbose_name='référence')),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(db_index=True, help_text='5 caractères en majuscules (lettres et chiffres)', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{5}$')], verbose_name='code'),
        ),
    ]
