# Generated by Django 5.2.3 on 2025-06-15 03:04

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_series_call_number_alter_series_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[inventory.models.validate_capitalized], verbose_name='nom'),
        ),
    ]
