# Generated by Django 5.2.3 on 2025-06-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('jp', 'Japonais'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('ar', 'Arabe')], default='fr', max_length=2, verbose_name='langue'),
        ),
    ]
