# Generated by Django 5.2.3 on 2025-06-15 03:35

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_series_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='call_number',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.text.LPad(django.db.models.functions.comparison.Cast('genre__id', models.CharField()), 2, models.Value('0')), 'code'), output_field=models.CharField(max_length=7, unique=True), verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('pt', 'Português'), ('jp', 'Japonais'), ('ch', 'Chinois'), ('ru', 'Russe'), ('ar', 'Arabe')], default='fr', max_length=2, verbose_name='langue'),
        ),
    ]
