# Generated by Django 5.2.3 on 2025-06-18 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def capitalize_genres(apps, schema_editor):
    Genre = apps.get_model('inventory', 'Genre')
    for genre in Genre.objects.all():
        genre.name = genre.name.capitalize()
        genre.save(update_fields=['name'])


def lowercase_genres(apps, schema_editor):
    Genre = apps.get_model('inventory', 'Genre')
    for genre in Genre.objects.all():
        genre.name = genre.name.lower()
        genre.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0027_book_added_by_alter_book_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ajouté par'),
        ),
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('bd', 'BD'), ('manga', 'Manga'), ('comics', 'Comics'), ('novel', 'Roman')], max_length=16, verbose_name='format'),
        ),
        migrations.RunPython(capitalize_genres, lowercase_genres),
    ]
