# Generated by Django 5.2.3 on 2025-06-17 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def update_conditions(apps, schema_editor):
    Book = apps.get_model('inventory', 'Book')

    Book.objects.filter(condition__in=[4, 3, 2, 1]).update(condition=1)  # très abimé
    Book.objects.filter(condition__in=[7, 6, 5]).update(condition=2)  # abimé
    Book.objects.filter(condition__in=[9, 8]).update(condition=3)  # bon
    Book.objects.filter(condition=10).update(condition=4)  # neuf


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_book_added_by_alter_series_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ajouté par'),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Neuf'), (3, 'Bon'), (2, 'Abimé'), (1, 'Très abimé')], verbose_name='état'),
        ),
        migrations.RunPython(update_conditions),
    ]
