# Generated by Django 5.2.14 on 2026-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_book_added_by_alter_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('bd', 'BD'), ('manga', 'Manga'), ('comics', 'Comics'), ('novel', 'Roman'), ('dvd', 'DVD')], max_length=16, verbose_name='format'),
        ),
    ]
