name: Renew SSL certificate

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  certificate:
    runs-on: [self-hosted, linux]
    environment: Production
    steps:
    - uses: actions/checkout@v3
    - name: Run certbot
      run: docker compose up certbot
      env:
        EMAIL: ${{ vars.EMAIL }}
        SITE_URL: ${{ vars.SITE_URL }}
