name: Deploy on VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    environment: Production
    steps:
    - uses: actions/checkout@v3
    - name: Build and restart docker
      run: docker compose up --build --detach --remove-orphans
      env:
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        EMAIL: ${{ vars.EMAIL }}
        SITE_URL: ${{ vars.SITE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}