name: Deploy on VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dump:
    uses: Lysquid/ClubBDManga/.github/workflows/dump.yml@main
  deploy:
    runs-on: [self-hosted, linux]
    environment: Production
    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      EMAIL: ${{ vars.EMAIL }}
      SITE_URL: ${{ vars.SITE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Build and restart docker compose
      run: docker compose up --build --detach --remove-orphans
    - name: Migrate
      run: docker compose run app python manage.py migrate