name: Deploy on VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
    - name: ssh on vps and update
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ github.event.repository.name }}
          git pull origin ${{ github.ref_name }}
          git checkout ${{ github.ref_name }}
          docker compose up --build --detach
