name: Shutdown the site

on:
  workflow_dispatch:

jobs:
  shutdown:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: Stop docker compose
      run: docker compose down